homeassistant:
  customize:
    package.node_anchors:
        Entità clima:                               &climate        climate.condizionatore_salone
        Presenza in casa:                           &family         group.famiglia
  
sensor:
  - platform: template
    sensors:
      thom_ac_salone:
        friendly_name: 'Indice di Thom Salone '
        unit_of_measurement: 'DI'
        value_template: >-     
            {% set climate = 'climate.condizionatore_salone'%}
            {{ (state_attr(climate,'current_temperature')|float(0) - (0.55-0.0055 * state_attr(climate,'current_humidity')|float(0))*(state_attr(climate,'current_temperature')|float(0) - 14.5))|round(1) }}


  - platform: template
    sensors:
      thom_esterno:
        friendly_name: 'Indice di Thom Esterno '
        unit_of_measurement: 'DI'
        value_template: >-     
            {% set temp_ext = states('sensor.weather_temperature')|float(0)%}
            {% set hum_ext = states('sensor.weather_humidity')|float(0) %}
            {{ (temp_ext - (0.55-0.0055 * hum_ext)*(temp_ext - 14.5))|round(1) }}

input_number:
  temperature_auto_on_summer_ac_salone:
    name: Temperatura Auto ON Estate Celsius
    icon: mdi:temperature-celsius
    mode: box
    min: 17
    max: 30
    step: 0.5
    unit_of_measurement: "°C"
  temperature_auto_off_summer_ac_salone:
    name: Temperatura Auto OFF Estate Celsius
    icon: mdi:temperature-celsius
    mode: box
    min: 17
    max: 30
    step: 0.5
    unit_of_measurement: "°C"
  humidity_auto_on_summer_ac_salone:
    name: Umidità Auto ON Estate Celsius
    icon: mdi:temperature-celsius
    mode: box
    min: 10
    max: 100
    step: 5
    unit_of_measurement: "%"
  humidity_auto_off_summer_ac_salone:
    name: Umidità Auto OFF Estate Celsius
    icon: mdi:temperature-celsius
    mode: box
    min: 10
    max: 100
    step: 5
    unit_of_measurement: "%"

  temperature_auto_on_winter_ac_salone:
    name: Temperatura Auto ON Inverno
    icon: mdi:temperature-celsius
    mode: box
    min: 17
    max: 30
    step: 0.5
    unit_of_measurement: "°C"
  temperature_auto_off_winter_ac_salone:
    name: Temperatura Auto OFF Inverno
    icon: mdi:temperature-celsius
    mode: box
    min: 17
    max: 30
    step: 0.5
    unit_of_measurement: "°C"

  temperature_auto_on_thom_ac_salone:
    name: Temperatura Auto ON Estate Thom
    icon: mdi:temperature-celsius
    mode: box
    min: 22
    max: 27
    step: 0.5
    unit_of_measurement: "DI"
  temperature_auto_off_thom_ac_salone:
    name: Temperatura Auto OFF Estate Thom
    icon: mdi:temperature-celsius
    mode: box
    min: 22
    max: 27
    step: 0.5
    unit_of_measurement: "DI"

  humidity_auto_on_ac_salone:
    name: Umidità Auto ON Estate Celsius
    icon: mdi:temperature-celsius
    mode: box
    min: 10
    max: 100
    step: 5
    unit_of_measurement: "%"
  humidity_auto_off_ac_salone:
    name: Umidità Auto OFF Estate Celsius
    icon: mdi:temperature-celsius
    mode: box
    min: 10
    max: 100
    step: 5
    unit_of_measurement: "%"

automation:

  - alias: Accensione Automatica  ac_salone   
    id: auto_on_ac_salone
    trigger:
    - platform: template
      value_template: >
        {% set mode = states('input_select.season_of_use_ac_salone') %}
        {%set climate = 'climate.condizionatore_salone' %}
        {%set thom_int = states('sensor.thom_ac_salone')|float(0)%}
        {{
          ('Estate Gradi Celsius' == mode and state_attr(climate,'current_temperature')|float(0) > states('input_number.temperature_auto_on_summer_ac_salone')|float(0) and state_attr(climate,'current_humidity')|int(0) > states('input_number.humidity_auto_on_summer_ac_salone')|int(0)) or 
          ('Inverno' == mode and state_attr(climate,'current_temperature')|float(0) < (states('input_number.temperature_auto_on_winter_ac_salone'))|float(0)) or 
          ('Estate Indice di thom' == mode and thom_int > (states('input_number.temperature_auto_on_thom_ac_salone'))|float(0)) or
          ('Umidità' == mode and state_attr(climate,'current_humidity')|int(0) > (states('input_number.humidity_auto_on_ac_salone'))|int(0))
        }}
      for:
        minutes: "{{ states('input_number.delay_auto_on_ac_salone')|int(0) }}"
    - platform: state
      entity_id: *family
      to: "home"
    - platform: time
      at: "input_datetime.auto_on_ac_salone"
    condition:
    - condition: state
      entity_id: *climate
      state: "off"
    - condition: time
      after: "input_datetime.auto_on_ac_salone"
      before: "input_datetime.auto_off_ac_salone"
    - condition: template
      value_template: >
        {% set mode = states('input_select.season_of_use_ac_salone') %}
        {%set climate = 'climate.condizionatore_salone' %}
        {%set thom_int = states('sensor.thom_ac_salone')|float(0)%}
        {{
          ('Estate Gradi Celsius' == mode and state_attr(climate,'current_temperature')|float(0) > states('input_number.temperature_auto_on_summer_ac_salone')|float(0) and state_attr(climate,'current_humidity')|int(0) > states('input_number.humidity_auto_on_summer_ac_salone')|int(0)) or 
          ('Inverno' == mode and state_attr(climate,'current_temperature')|float(0) < (states('input_number.temperature_auto_on_winter_ac_salone'))|float(0)) or 
          ('Estate Indice di thom' == mode and thom_int > (states('input_number.temperature_auto_on_thom_ac_salone'))|float(0)) or
          ('Umidità' == mode and state_attr(climate,'current_humidity')|int(0) > (states('input_number.humidity_auto_on_ac_salone'))|int(0))
        }}
    action:
    - choose:
      - alias: ACCENSIONE LEGATA ALLA PRESENZA
        conditions: 
        - condition: state
          entity_id: input_boolean.presence_ac_salone
          state: "on"
        - condition: state
          state: "home"
          entity_id: *family
        sequence:
        - alias: VERIFICA SE CONTROLLO FINESTRA ATTIVO
          if: "{{is_state('input_boolean.check_window_ac_salone','on')}}"
          then:
            - service: script.check_windows_ac_salone
              data: {}
          else:
            - service: script.check_ext_temp_climate_on_ac_salone
              data: {}           
      - alias: ACCENSIONE SENZA PRESENZA
        conditions:
        - condition: state
          entity_id: input_boolean.presence_ac_salone
          state: "off"
        sequence:
        - alias: VERIFICA SE CONTROLLO FINESTRA ATTIVO
          if: "{{is_state('input_boolean.check_window_ac_salone','on')}}"
          then:
            - service: script.check_windows_ac_salone
              data: {}
          else:
            - service: script.check_ext_temp_climate_on_ac_salone
              data: {}
  # SPEGNIMENTO
  - alias: Spegnimento automatico ac_salone
    id: auto_off_ac_salone
    trigger:
    - platform: template
      value_template: >
        {% set mode = states('input_select.season_of_use_ac_salone') %}
        {%set climate = 'climate.condizionatore_salone' %}
        {%set thom_int = states('sensor.thom_ac_salone')|float(0)%}
        {{
          ('Estate Gradi Celsius' == mode and state_attr(climate,'current_temperature')|float(0) < states('input_number.temperature_auto_off_summer_ac_salone')|float(0) and state_attr(climate,'current_humidity')|int(0) < states('input_number.humidity_auto_off_summer_ac_salone')|int(0)) or 
          ('Inverno' == mode and state_attr(climate,'current_temperature')|float(0) > (states('input_number.temperature_auto_off_winter_ac_salone'))|float(0)) or 
          ('Estate Indice di thom' == mode and thom_int < (states('input_number.temperature_auto_off_thom_ac_salone'))|float(0)) or
          ('Umidità' == mode and state_attr(climate,'current_humidity')|int(0) < (states('input_number.humidity_auto_off_ac_salone'))|int(0))
        }}
      for:
        minutes: "{{ states('input_number.delay_auto_off_ac_salone')|int(0) }}"
    - platform: time
      at: "input_datetime.auto_off_ac_salone"
    - platform: state
      entity_id: *family
      not_to: "home"
    action:
    - service: script.climate_turn_off_ac_salone
      data: {}